apiVersion: v1
kind: Service
metadata:
  name: echo-server
spec:
  selector:
    app: echo-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      name: echo-server
      labels:
        app: echo-server
        version: v1
    spec:
      containers:
        - name: echo-server
          image: hashicorp/http-echo:latest
          args:
            - -text="echo world"
            - -listen=:8080
          ports:
            - containerPort: 8080
              name: http
