apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: finance-v1
spec:
  podSelector:
    matchLabels:
      app: finance-server
      version: v1
  listeners:
    - portMapping:
        port: 80
        protocol: http
      healthCheck:
        protocol: http
        path: '/finance'
        healthyThreshold: 2
        unhealthyThreshold: 2
        timeoutMillis: 2000
        intervalMillis: 5000
  serviceDiscovery:
    dns:
      hostname: finance-server.app-mesh-demo.svc.cluster.local
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: finance-v2
spec:
  podSelector:
    matchLabels:
      app: finance-server
      version: v2
  listeners:
    - portMapping:
        port: 80
        protocol: http
      healthCheck:
        protocol: http
        path: '/finance'
        healthyThreshold: 2
        unhealthyThreshold: 2
        timeoutMillis: 2000
        intervalMillis: 5000
  serviceDiscovery:
    dns:
      hostname: finance-server.app-mesh-demo.svc.cluster.local
