apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  name: finance
spec:
  listeners:
    - portMapping:
        port: 80
        protocol: http
  routes:
    - name: finance-server-route
      httpRoute:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeRef:
                name: finance-v1
              weight: 10
            - virtualNodeRef:
                name: finance-v2
              weight: 90
